# Attribution goes to @pklaschka for this awesome action.
# Taken from the chat-xd-plugin workflows
# https://github.com/pklaschka/chat-xd-plugin/ (c) 2020 Pablo Klaschka (MIT-Licensed)

name: Lint

on: push

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: 'npm'

      # Eslint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      # Remove, when setup-node action supports specifying the node version
      - name: Install npm v7 ⬆
        run: npm install --global npm@v7

      - name: Run linters
        uses: wearerequired/lint-action@v1.10.0
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          prettier: true
