name: Build and release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    name: Release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 📥
        uses: actions/checkout@v3.0.2
      - name: Setup Node 💿
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16

      - name: Build and Release Electron app 🗜
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          release: true
